### ISSUE TITLE
Allow void functions

### ISSUE THREAD

**Issue by JustusAdam** [ohua-dev/ohua-core#13]
It has become apparent that it is necessary to support functions with no return. Perhaps we can abuse the `unit` hack again.

**Comment by sertel** [comment]
Here is the error report such that we can derive a test case:

This code has problems compiling:

```rust
ns some_ns;

use sf addition (produce, consume);

fn main() {
    let result = produce();
    consume(result)
}
```
It throws this error message:

```
[felix@Samaritan] $ ohuac build foobar.ohuac
[Debug] Lowering alang expr: AExpr {unAExpr = LetF "a" (AExpr {unAExpr = ApplyF (AExpr {unAExpr = VarF (Sf addition/consume Nothing)}) (AExpr {unAExpr = VarF (Sf addition/produce Nothing)})}) (AExpr {unAExpr = VarF (Local "a")})}
[Debug] Lowering Let -->
[Debug] Current state: []
[Error] Var must be local or env, was Sf addition/produce Nothing
```
The formatted version of the expression looks as follows:
```
AExpr {
  unAExpr = LetF "a" (AExpr { unAExpr = ApplyF (AExpr { unAExpr = VarF (Sf addition/consume Nothing)}) 
                                               (AExpr { unAExpr = VarF (Sf addition/produce Nothing)})}) 
                     (AExpr {unAExpr = VarF (Local "a")})}
```
According to this expression, the code actually looks as follows:
```rust
ns some_ns;

use sf addition (produce, consume);

fn main() {
    consume(produce());
}
```
In any case, the lowering pass seems to expect a `Var` as the second argument to `Apply` but finds `Sf`.
I already talked to @JustusAdam about this and this seems to be a problem with functions that do not have arguments.

**Comment by JustusAdam** [comment]
What you are talking about is ohua-dev/alang-clike-parser#7 which is already fixed. I will make a new release for ohuac soon which will include this fix.

What I mean by `void` functions is something like this

```rust
fn foo (a) {
    compute(a);
    flush();
}

```

Which I would like to desugar to 

```hs
let foo = \a -> let _ = compute a in let _ = flush () in ()
```

**Comment by sertel** [comment]
(I was not sure whether it was already taken care of, so I added it to this issue.)

Sounds good to me.

**Comment by sertel** [comment]
@JustusAdam is still a valid work item? I know that I fixed this in core at least.

**Comment by JustusAdam** [comment]
I think so.
