### ISSUE TITLE
A simpler DF-lowering for if-then-else

### ISSUE THREAD

**Issue by sertel** [ohua-dev/ohua-core#21]
The current lowering requires the backend to implement a dataflow operator called `bool` which is supposed to have 3 outputs:

1. context arc for the `if` branch
2. context arc for the `else` branch
3. selector for the `select` operator

There is a simpler lowering that just uses whatever enters the `bool` operator now and dispatches it to:

1. the `if` branch
2. the `neg` function that in turn dispatches its result to the `else` branch
3. the `select` operator

This removes the weird `bool` operator from the backend implementation in favor of the simple `neg` function (which might be useful to have anyhow since we have `ohua.lang/true` and `ohua.lang/false` as functions).

**Comment by JustusAdam** [comment]
Do we even need `if` then? Would a `duplicate :: a -> (a, a)` not be enough?

**Comment by sertel** [comment]
No, we don't need an `if` but an arc that connects to the `if` branch.
We also don't need a `duplicate`.
