### ISSUE TITLE
Provide Backend with additional information regarding operator types

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/ohua-core#25]
The compiler internally differentiates between operators of type `DFFunction` and `EmbedSf`, but this differentiation gets lost when the algorithm information is passed to the backend via a `DFGraph`.

As it is necessary for the code generation to know which operators are stateful functions and which are dataflow operators, it would be helpful if this information would be passed on to the backend.

**Comment by sertel** [comment]
This was fixed.
