### ISSUE TITLE
Non-exhaustive patterns in function bindingFromLit

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/ohua-core#28]
When trying to compile the following algorithm:
```
ns some_ns;

use sf conditionals::iftest::{modify_string_positive, modify_string_negative};

fn main(ctrl: bool, inp: String) -> String {
    if (ctrl) {
        modify_string_positive(inp)
    } else {
        modify_string_negative(inp)
    }
}
```

`ohuac` emits the following error message, originating from [this file](https://github.com/ohua-dev/ohua-core/blob/b96264bdc2e2a01a71bab1f6a96ceb53910e87e1/core/src/Ohua/ALang/Util.hs#L79):
```
ohuac: src/Ohua/ALang/Util.hs:(79,5)-(81,65): Non-exhaustive patterns in function bindingFromLit
```

---
For reference: I am using the latest `ohuac` version, modified to use the latest `ohua-core` version.

**Comment by sertel** [comment]
Running `ohuac build --dump-stage "alang-resolved" if_envarcs.ohuac` outputs:
```
let ctrl = $0 in
let inp = $1 in
ohua.lang/if ctrl (λ _ -> conditionals.iftest/modify_string_positive inp)
  (λ _ -> conditionals.iftest/modify_string_negative inp)
```

**Comment by JustusAdam** [comment]
Jo, that's your `Non-exhaustive pattern` though @sertel 😛 

(Just kidding, will have a look at it next week.)

**Comment by sertel** [comment]
I know ;)

Thanks!
