### ISSUE TITLE
[Feature] Support for recursion

### ISSUE THREAD

**Issue by sertel** [ohua-dev/ohua-core#3]
Many higher-order functions can be implemented via tail-recursion. If we manage to support this then we can easily extend our language.

**Comment by sertel** [comment]
The work that remains is best described in the following paper:
http://dl.acm.org/citation.cfm?id=968422

**Comment by JustusAdam** [comment]
I am dealing with a test case now that recursively uses variables. But I assume the test case was actually supposed to ensure that precisely that does not happen.

```clj
(let [[one two] (accept "some-id")]
  (let [one (read one)] (parse one two)))
```

I assume since we will support recursion this should be either be recursion or not allowed?
