### ISSUE TITLE
Wrong contextualization of sfn used in smap

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/ohua-core#30]
[This](https://pastebin.com/1BGnA594) algorithm, which compiles to [this output](https://pastebin.com/29aumUHr) ([DFLang](https://pastebin.com/ZhD1xS6C), [ALang](https://pastebin.com/Wrni02N6)), is not correctly translated by `ohuac` as it contains a stateful function `generate_value` that is not part of the `smap` context, even though it should be.

**Comment by sertel** [comment]
The problem is the fix for exponentiation. It does not take function literals into account and as such thinks that this is some input variable although it isn't.

**Comment by sertel** [comment]
The bug is in `findLonelyLiterals` of `Ohua.ALang.Util`. The point is that `unitFn` has Function Literals which are *not* vars. Fixing this will contextify calls to `unitFn`.
