### ISSUE TITLE
[Feature] Custom compiler passes

### ISSUE THREAD

**Issue by JustusAdam** [ohua-dev/ohua-core#4]
Add facilities to support specifying custom passes when invoking the compiler.

### Locations

Suggestions for locations where to trigger/insert custom passes:

1. As a no brainer each IR should allow custom passes, aka one each at least for ALang, DFLang, the Graph (and later DAGLang)
1. ALang:
    - raw
    - normalized
    - optimized
1. DFLang:
    - optimized
    - unoptimized
1. DAGLang 
    - ?
1. Graph

**Comment by sertel** [comment]
Was already implemented.
