### ISSUE TITLE
Commit generated .cabal file into repo

### ISSUE THREAD

**Issue by rahulmutt** [ohua-dev/ohua-core#8]
With `etlas-1.3.0.0`'s upgraded build system, you can specify the following `cabal.project` file in `ohua-jvm-integration`:

```
packages: .

source-repository-package
  type: git
  location: https://github.com/ohua-dev/ohua-core
  commit: 72b004347d2c0dff139b4f3213e98030fc0e1b79
```

This way, all a person needs to do is run `etlas build` inside of `ohua-jvm-integration` and everything will just work.

But the above won't work *until* there is a `.cabal` file present in this repo. As of now, there is just a `package.yaml` which `etlas` doesn't recognize so it will complain that there's no `.cabal` files present.

**Comment by JustusAdam** [comment]
I usually don't like to commit generated files to repos. But this seems like a compelling reason to do so.
